version: '3.8'
services:
  postgres:
    container_name: postgres-drd
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drd
    volumes:
      - ./pgdata:/var/lib/data
    restart: on-failure
    ports:
      - '5432:5432'
